### ISSUE TITLE
python 2 vs 3 behaviour

### ISSUE THREAD

**Issue by dmnfarrell** [simon-anders/htseq#23]
I've just been trying HTSeq 0.7 on python 3. I've noted some differences in string handling. For example this statement works on python 2 but not on 3, unless we encode the byte object.

```
seq = 'AAATTTGCCGCG'
seq = seq.encode() # needed for python 3
myseq = HTSeq.Sequence(seq, 'name')
```

The error Argument 'seq' has incorrect type (expected bytes, got str) is thrown on python 3.5.
The same applies when reading a sam file using HTSeq.SAM_Reader(samfile). The resulting iterator yields bytes instead of strings for the sequence field. These issues can be handled by using seq.decode() and seq.encode() methods but not sure if this should be needed.

Could you clarify if this behaviour is intended or if its a bug?
Thanks for updating your package for Python 3 support BTW.

**Comment by iosonofabio** [comment]
Hi Damien,
As you may know string handling has improved a lot in Python 3 and a char is not a byte anymore. The "downside" is that people realize that there was confusion before :-)

HTSeq uses pysam to manipulate Samfiles, and pysam switched to bytes, so do we. It is a good idea to keep e.g. nucleotide or amino acid sequences as bytes because their alphabet is very small but they can get quite long.

I think the sequence NAME should still be a string (now UTF-8) because those are short and read mostly by humans

Does it make sense?

That answers your question?

**Comment by dmnfarrell** [comment]
Hi Fabio

Ok if this is the new behaviour that's fine. However doesn't this mean that the inputs to some methods will not be the same in python 2 and 3. I'd like to be able to support both versions so I just wanted to check first.

thanks

**Comment by iosonofabio** [comment]
You are right that API differs a bit btw python2 and 3. I'll keep this issue open for the time being to investigate whether there's a decent way of improving this behaviour. Thanks!

**Comment by iosonofabio** [comment]
This is connected to issue #28 and is basically a question of whether sequences are bytes or unicodes... will need to look up some docs as of how to be consistent and fast at the same time

**Comment by iosonofabio** [comment]
6176568 implements a raw iterator that is fast and a slow iterator that is nice, because `Sequence` is fairly low level and Cython we keep its input as `bytes` for now. This differs from other libraries but is quite fast.
