### ISSUE TITLE
HTSeq output files

### ISSUE THREAD

**Issue by coolmak32** [simon-anders/htseq#75]
Hello , I ran a bam file and a sam file through HTSeq for the read counts. 
The following the output of the BAM file with no numeric value for the read counts:
krishna@dntdaretouchit:/mnt/e/cannon$ head countread.text XF:Z:__ambiguous[ENSMUSG00000098178.1+ENSMUSG00000106106.2] XF:Z:__ambiguous[ENSMUSG00000098178.1+ENSMUSG00000106106.2] XF:Z:__alignment_not_unique XF:Z:__alignment_not_unique XF:Z:__alignment_not_unique XF:Z:__alignment_not_unique XF:Z:__no_feature XF:Z:__no_feature XF:Z:__alignment_not_unique XF:Z:__alignment_not_unique

And this is the output format from the SAM file:

chr1 3206084 255 1S139M = 3206084 -139 NTACAGTTAACCAACTTATACAGTTAACCAACTCCTACACTAGGTTCCTGAGCATTTCCTTAAACTTGCTAGTTCTGGTTTCCTGGCATGTGAGAGTAAGTCACATGGTAGGAGGCTGCCTTTCTATCJJJFJJFJJJAJFJJJFJFFJFJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJJFJJJJJA<<JJJJJJJJJJJJJJJJJJJJJJJJJJJJJJFJJJJJJJFFJJJJJFJFJJJJJJJJFJJJJJJJJJJJJJJAFAAA NH:i:1 HI:i:1 AS:i:276 nM:i:0 XF:Z:ENSMUSG00000051951.5
GWNJ-0965:181:GW180227920:7:2124:9881:65265 163 chr1 3206084 255 139M1S = 3206084 139 TACAGTTAACCAACTTATACAGTTAACCAACTCCTACACTAGGTTCCTGAGCATTTCCTTAAACTTGCTAGTTCTGGTTTCCTGGCATGTGAGAGTAAGTCACATGGTAGGAGGCTGCCTTTCTATCATTCAATTTTAGN 

I am having a hard time to interpret these file for the count numbers. The output from the BAM file looks absurd. I'd prefer to work with BAM files.

**Comment by simon-anders** [comment]
I don't understand what you are trying to do. 

The "samout" function is meant for debugging. If you are just interested in a count table, don't use it.

The table is printed on the console.

**Comment by coolmak32** [comment]
Hello Simon, 
My objective is to procure the read counts and then find out genes that have circadian expression. 
With the command mentioned below, I am not getting the numeric value for the read counts. In my terminal I see the numbers but not in the file generated by HTSeq in my directory.
htseq-count -m union -f bam -s no -r pos crzt2-1caligned.sam geneassembly.gff3 -o countfile.text

**Comment by simon-anders** [comment]
Try

```
htseq-count -m union -f bam -s no -r pos crzt2-1caligned.bam geneassembly.gff3 > countfile.text
```

Note `>` instead of `-o`!

**Comment by iosonofabio** [comment]
-o is used for annotated SAM files, not for the counts. The counts are currently only flushed to standard output (the terminal), though this might change in the future if there's interest.

**Comment by jasonsaunderswilliams** [comment]
Hi all, I am also trying to get a count text file using sorted BAM alignments from STAR and .GFF file as input. When I use the following command:
sudo docker run -ti --rm -v /home/ubuntu/work/Jason/RNASeq_Continuum:/home/ubuntu/work/Jason/RNASeq_Continuum -v /home/ubuntu/work/Jason:/inputfiles genomicpariscentre/htseq htseq-count -f bam /home/ubuntu/work/Jason/RNASeq_Continuum/STAR_Alignments/RNASeq_i8Aligned.toTranscriptome.out.bam /home/ubuntu/work/Jason/RNASeq_Continuum/STAR_Alignments/gencode.v30.chr_patch_hapl_scaff.annotation.gff3 > i8.txt

What happens when I run this is that it doesn't process, the cursor moves to the next line and nothing happens. 

When I run the command without the > i8.txt I get what I think is the count output, however, I can only scroll up so far to the top which is this:

ENSG00000285260.1	0
ENSG00000285261.1	0
ENSG00000285263.1	0
ENSG00000285264.1	0
ENSG00000285266.1	0
ENSG00000285267.1	0
ENSG00000285268.1	0
ENSG00000285269.2	0
ENSG00000285270.1	0
ENSG00000285271.1	0
......
__no_feature	7368043
__ambiguous	0
__too_low_aQual	0
__not_aligned	0
__alignment_not_unique	90300469

I apologise if my I have made an amateurish mistake in my original command. Any help would be much appreciated. By the way, can I specify the file path where the .txt count file is outputted to? I am using a docker in a shell and I usually do this using other programs...

Thanks in advance,

Jason

**Comment by simon-anders** [comment]
Jason: Please do not append to closed issues; open a new one.

However, to be honest, your question does not sound like a problem with htseq-count. Rather, you need to learn more about the basics of working with the command line and with docker. Are you sure your i8.txt file is empty?
Rather than us trying to diagnose your issue remotely, it will be far easier if you asked any local colleague at your institute who has a bit more experience with working with Unix systems.

**Comment by jasonsaunderswilliams** [comment]
Thanks Simon. I will check at our end and I will be sure not to append a closed issue in the future.

Best wishes,

Jason
